### ISSUE TITLE
Error: No msdfgen binary for platform linux.

### ISSUE THREAD

**Issue by PainKKKiller** [Jam3/msdf-bmfont#10] opened 2017-03-27 08:53 UTC
Unable to run msdf-bmfont on Ubuntu 16.04, in msdf-bmfont/bin no binary for Linux

**Comment by arilotter** [comment] 2017-04-03 06:49
Issue is a duplicate of #4. I'll try to get around to it soon, but it might yet be a few months.

**Closed by arilotter** 2017-04-03 06:49 UTC
